import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [faviconVar, setFaviconVar] = useState(
    Math.floor(Math.random() * 3) + 1
  );

  useEffect(() => {
    if (faviconVar === 3) {
      setFaviconVar(Math.floor(Math.random() * 2) + 1);
    } else {
      setFaviconVar(faviconVar + 1);
    }
  }, []);

  // useEffect(() => {
  //   if (faviconVar === 3 || faviconVar === 2) {
  //     setFaviconVar(1);
  //   } else if (faviconVar === 2 || faviconVar === 1) {
  //     setFaviconVar(3);
  //   } else {
  //     setFaviconVar(2);
  //   }
  // }, []);

  // console.log(faviconVar);

  return (
    <div className={styles.container}>
      <Head>
        <title>Otavio Vidal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`favicon-${faviconVar}.ico`} />
      </Head>

      <main className={styles.main}>
        <Link href="/about">
          <a>About Us</a>
        </Link>
      </main>
    </div>
  );
}
