import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Otavio Vidal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-1.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/about">
          <a>About Us</a>
        </Link>
      </main>
    </div>
  );
}
